#----------------------------------------------------------
#--  HACK: Monokai Pro (Filter Spectrum)
#----------------------------------------------------------

[mgr]
cwd = { fg = "#5AD4E6" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_symbol = " Finding: "
find_keyword = { fg = "#FC618D", bold = true, italic = true, underline = true }
find_position = { fg = "#948AE3", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { fg = "#5AD4E6", italic = true }

# Marker
marker_copied = { fg = "#7BD88F", bg = "#7BD88F" }
marker_cut = { fg = "lightred", bg = "lightred" }
marker_marked = { fg = "#948AE3", bg = "#948AE3" }
marker_selected = { fg = "#FC618D", bg = "#FC618D" }

# Count
count_copied = { fg = "#222222", bg = "#7BD88F" }
count_cut = { fg = "#222222", bg = "#FC618D" }
count_selected = { fg = "#222222", bg = "#FCE566" }

# Border
border_symbol = "│"
border_style = { fg = "#525053" }

# Tabs
[tabs]
active = { fg = "#222222", bg = "#FCE566", bold = true }
inactive = { fg = "#FCE566", bg = "#222222" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# Modes
[mode]
# Normal mode
normal_main = { fg = "#222222", bg = "#FCE566", bold = true }
normal_alt = { fg = "#FCE566", bg = "#363537" }

# Select mode
select_main = { fg = "#222222", bg = "#948AE3", bold = true }
select_alt = { fg = "#948AE3", bg = "#363537" }

# Unset mode
unset_main = { bg = "#FC618D", bold = true }
unset_alt = { fg = "#FC618D", bg = "gray" }

# Status bar
[status]
overall = {}
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep = { fg = "#525053" }
perm_type = { fg = "#7BD88F" }
perm_read = { fg = "#FCE566" }
perm_write = { fg = "#FC618D" }
perm_exec = { fg = "#5AD4E6" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#5AD4E6", bg = "#222222" }
progress_error = { fg = "#FC618D", bg = "#222222" }

# Which
[which]
cols = 3
mask = { bg = "#222222" }
cand = { fg = "lightcyan" }
rest = { fg = "#525053" }
desc = { fg = "lightmagenta" }
separator = "  "
separator_style = { fg = "#525053" }

# Confirmation
[confirm]
border = { fg = "#FCE566" }
title = { fg = "#FCE566" }
content = {}
list = {}
btn_yes = { reversed = true }
btn_no = {}
btn_labels = ["  [Y]es  ", "  (N)o  "]

# Spotter
[spot]
border = { fg = "#5AD4E6" }
title = { fg = "#5AD4E6" }

# Table
tbl_col = { fg = "#5AD4E6" }
tbl_cell = { fg = "#FCE566", reversed = true }

# Norifications
[notify]
title_info = { fg = "#7BD88F" }
title_warn = { fg = "#FCE566" }
title_error = { fg = "#FC618D" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# Picker
[pick]
border = { fg = "#5AD4E6" }
active = { fg = "#948AE3", bold = true }
inactive = {}

# Input
[input]
border = { fg = "#5AD4E6" }
title = {}
value = {}
selected = { reversed = true }

# Completion
[cmp]
border = { fg = "#5AD4E6" }
active = { reversed = true }
inactive = {}

# Icons
icon_file = ""
icon_folder = ""
icon_command = ""

# : Task manager {{
[tasks]
border = { fg = "#5AD4E6" }
title = {}
hovered = { fg = "#948AE3", underline = true }

# Help menu
[help]
on = { fg = "#5AD4E6" }
run = { fg = "#948AE3" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "#222222", bg = "#F7F1FF" }

# File-specific styles
[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "#FCE566" },

  # Media
  { mime = "{audio,video}/*", fg = "#7BD88F" },

  # Archives
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#FC618D" },

  # Documents
  { mime = "application/{pdf,doc,rtf}", fg = "#5AD4E6" },

  # Empty files
  { mime = "inode/empty", fg = "#FC618D" },

  # Special files
  { url = "*", is = "orphan", bg = "#FC618D" },
  { url = "*", is = "exec", fg = "#7BD88F" },

  # Dummy files
  { url = "*", is = "dummy", bg = "#FC618D" },
  { url = "*/", is = "dummy", bg = "#FC618D" },

  # Fallback
  { url = "*/", fg = "#FD9353", bold = true },
]
